### ISSUE TITLE
Default Calculator returns different number of features in 1.0.0 and 1.1.1

### ISSUE THREAD

**Issue by shayakhmetov** [mordred-descriptor/mordred#51]
```
from mordred import Calculator
from mordred import descriptors
c = Calculator(descriptors)
len(c(molecule).fill_missing(np.nan).asdict())
```
returns different lengths in mordred 1.0.0 and mordred 1.1.1 as well as some descriptors are missing. Is it possible to fix default descriptors in the future releases for compatibility reasons?

**Comment by philopon** [comment]
Dear shayakhmetov,

In v1.1.0, some descriptors were newly implemented and 2 descriptors were deleted from preset since these are trivial.
It is expected that such changing are frequently occurred in future.
However, it is also important to keep backward compatibility. Thus, "descriptor versioning" feature was introduced in v1.1.0.

```.py
calc = Calculator(descriptors, version="1.0.0")
```

Also, You also be able to dump descriptor set to json (or other serializable file such as pickle) and restore.

```.py
json.dump(calc.to_json(), open('descriptors.json', 'w'))
# or pickle.dump(calc.to_json(), open('descriptors.pkl', 'wb'))

Calculator.from_json(json.load(open('descriptors.json', 'r')))
# or Calculator.from_json(pickle.load(open('descriptors.pkl', 'rb')))
```

I hope this helps you.

Thanks,

**Comment by philopon** [comment]
If you have any more question in this topic, please re-open freely.
